// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/upload": {
    params: {};
  };
  "/resume/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/upload" | "/resume/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/upload.tsx": {
    id: "routes/upload";
    page: "/upload";
  };
  "routes/resume.tsx": {
    id: "routes/resume";
    page: "/resume/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
  "routes/upload": typeof import("./app/routes/upload.tsx");
  "routes/resume": typeof import("./app/routes/resume.tsx");
};